export const TRUST_PROFILE = {
  status: "OVER-RELIANT",
  totalDecisions: 20,
  overRelianceRate: 35,
  underRelianceRate: 10,
  threshold: 20,
  explanation:
    "You tend to follow AI recommendations even when they may be incorrect. The system has adjusted your explanations to emphasise uncertainty.",
  calibrationSeries: [
    { decision: 1, over: 10, under: 5 },
    { decision: 2, over: 15, under: 5 },
    { decision: 3, over: 18, under: 8 },
    { decision: 4, over: 20, under: 8 },
    { decision: 5, over: 22, under: 10 },
    { decision: 6, over: 25, under: 10 },
    { decision: 7, over: 24, under: 9 },
    { decision: 8, over: 28, under: 9 },
    { decision: 9, over: 30, under: 11 },
    { decision: 10, over: 32, under: 10 },
    { decision: 11, over: 31, under: 12 },
    { decision: 12, over: 33, under: 11 },
    { decision: 13, over: 34, under: 10 },
    { decision: 14, over: 36, under: 9 },
    { decision: 15, over: 35, under: 10 },
    { decision: 16, over: 37, under: 11 },
    { decision: 17, over: 36, under: 10 },
    { decision: 18, over: 34, under: 9 },
    { decision: 19, over: 35, under: 10 },
    { decision: 20, over: 35, under: 10 },
  ],
  recentDecisions: [
    {
      id: "D-020",
      date: "2026-08-22",
      applicant: "Kumari Fernando",
      aiRecommendation: "Approve",
      officerDecision: "Approve",
      outcome: "Correct",
      match: true,
    },
    {
      id: "D-019",
      date: "2026-08-21",
      applicant: "Ruwan Perera",
      aiRecommendation: "Reject",
      officerDecision: "Approve",
      outcome: "Incorrect",
      match: false,
    },
    {
      id: "D-018",
      date: "2026-08-20",
      applicant: "Sanduni Wickramasinghe",
      aiRecommendation: "Approve",
      officerDecision: "Approve",
      outcome: "Correct",
      match: true,
    },
    {
      id: "D-017",
      date: "2026-08-19",
      applicant: "Chathura Silva",
      aiRecommendation: "Approve",
      officerDecision: "Reject",
      outcome: "Correct",
      match: false,
    },
    {
      id: "D-016",
      date: "2026-08-18",
      applicant: "Nadeesha Gunasekara",
      aiRecommendation: "Reject",
      officerDecision: "Reject",
      outcome: "Correct",
      match: true,
    },
    {
      id: "D-015",
      date: "2026-08-17",
      applicant: "Amal Jayawardena",
      aiRecommendation: "Approve",
      officerDecision: "Approve",
      outcome: "Incorrect",
      match: true,
    },
    {
      id: "D-014",
      date: "2026-08-16",
      applicant: "Ishara Bandara",
      aiRecommendation: "Reject",
      officerDecision: "Approve",
      outcome: "Incorrect",
      match: false,
    },
    {
      id: "D-013",
      date: "2026-08-15",
      applicant: "Tharindu Pathirana",
      aiRecommendation: "Approve",
      officerDecision: "Approve",
      outcome: "Correct",
      match: true,
    },
    {
      id: "D-012",
      date: "2026-08-14",
      applicant: "Malini Rathnayake",
      aiRecommendation: "Approve",
      officerDecision: "Reject",
      outcome: "Incorrect",
      match: false,
    },
    {
      id: "D-011",
      date: "2026-08-13",
      applicant: "Kasun Mendis",
      aiRecommendation: "Reject",
      officerDecision: "Reject",
      outcome: "Correct",
      match: true,
    },
  ],
}

export const STATUS_META = {
  "OVER-RELIANT": {
    label: "OVER-RELIANT",
    className:
      "border-transparent bg-orange-500/15 text-orange-700 dark:text-orange-300",
  },
  "UNDER-RELIANT": {
    label: "UNDER-RELIANT",
    className:
      "border-transparent bg-sky-500/15 text-sky-700 dark:text-sky-300",
  },
  "WELL-CALIBRATED": {
    label: "WELL-CALIBRATED",
    className:
      "border-transparent bg-emerald-500/15 text-emerald-700 dark:text-emerald-300",
  },
}
