export const OFFICER = {
  name: "Nimali Jayasuriya",
  branch: "Gampaha Central",
  portfolioId: "PF-GAM-014",
}

export const PORTFOLIO_STATS = {
  ewsAlertCount: 7,
  overdueCount: 11,
  par30: 6.4,
  activeLoans: 48,
  dueToday: 9,
}

export const ACTIVE_LOANS = [
  {
    id: "LN-88421",
    borrower: "Kumari Fernando",
    product: "Group Enterprise",
    outstanding: 86500,
    nextDue: "2026-08-21",
    status: "ews",
    daysLate: 12,
    alertId: "EWS-1042",
  },
  {
    id: "LN-88390",
    borrower: "Ruwan Perera",
    product: "Individual Working Capital",
    outstanding: 124000,
    nextDue: "2026-08-22",
    status: "current",
    daysLate: 0,
    alertId: null,
  },
  {
    id: "LN-88211",
    borrower: "Sanduni Wickramasinghe",
    product: "Agricultural Seasonal",
    outstanding: 54000,
    nextDue: "2026-08-21",
    status: "overdue",
    daysLate: 34,
    alertId: "EWS-1038",
  },
  {
    id: "LN-88104",
    borrower: "Ajith Bandara",
    product: "Group Enterprise",
    outstanding: 31200,
    nextDue: "2026-08-23",
    status: "current",
    daysLate: 0,
    alertId: null,
  },
  {
    id: "LN-88077",
    borrower: "Fathima Nizar",
    product: "Housing Repair",
    outstanding: 198000,
    nextDue: "2026-08-24",
    status: "ews",
    daysLate: 8,
    alertId: "EWS-1045",
  },
]

export const COLLECTION_ROUTE = [
  {
    id: "STOP-1",
    loanId: "LN-88211",
    borrower: "Sanduni Wickramasinghe",
    village: "Yakkala",
    amountDue: 4200,
    priority: 1,
    reason: "PAR30 — 34 days late",
    phone: "071 556 2204",
  },
  {
    id: "STOP-2",
    loanId: "LN-88421",
    borrower: "Kumari Fernando",
    village: "Kirindivita",
    amountDue: 3500,
    priority: 2,
    reason: "EWS compounding risk",
    phone: "077 412 8891",
  },
  {
    id: "STOP-3",
    loanId: "LN-88077",
    borrower: "Fathima Nizar",
    village: "Ganemulla",
    amountDue: 6800,
    priority: 3,
    reason: "EWS — social signal decay",
    phone: "075 220 1188",
  },
  {
    id: "STOP-4",
    loanId: "LN-88390",
    borrower: "Ruwan Perera",
    village: "Miriswatta",
    amountDue: 5100,
    priority: 4,
    reason: "Due today",
    phone: "071 223 4410",
  },
]

export const ALERTS = {
  "EWS-1042": {
    id: "EWS-1042",
    loanId: "LN-88421",
    borrower: "Kumari Fernando",
    nic: "198765432V",
    phone: "077 412 8891",
    product: "Group Enterprise",
    group: "Kirindivita Women's Group 12",
    disbursed: "2025-11-04",
    outstanding: 86500,
    installment: 3500,
    cycle: "Weekly",
    officer: OFFICER.name,
    distressProbability: 78,
    threshold: 60,
    paymentVelocity: {
      unit: "days late",
      slopeLabel: "Worsening at 2.4 days per installment",
      series: [0, 1, 2, 4, 7, 9, 12],
    },
    socialDecay: {
      unit: "group engagement score",
      slopeLabel: "Decaying at −6.1 points per cycle",
      series: [92, 88, 81, 74, 61, 52, 44],
    },
    correlation: {
      aligned: true,
      label: "Both signals declining simultaneously — Compounding Risk",
    },
  },
  "EWS-1038": {
    id: "EWS-1038",
    loanId: "LN-88211",
    borrower: "Sanduni Wickramasinghe",
    nic: "199012345V",
    phone: "071 556 2204",
    product: "Agricultural Seasonal",
    group: "Individual",
    disbursed: "2026-02-18",
    outstanding: 54000,
    installment: 4200,
    cycle: "Monthly",
    officer: OFFICER.name,
    distressProbability: 86,
    threshold: 60,
    paymentVelocity: {
      unit: "days late",
      slopeLabel: "Worsening at 4.1 days per installment",
      series: [2, 5, 11, 18, 24, 30, 34],
    },
    socialDecay: {
      unit: "group engagement score",
      slopeLabel: "Decaying at −3.2 points per cycle",
      series: [70, 66, 64, 58, 55, 51, 48],
    },
    correlation: {
      aligned: true,
      label: "Both signals declining simultaneously — Compounding Risk",
    },
  },
  "EWS-1045": {
    id: "EWS-1045",
    loanId: "LN-88077",
    borrower: "Fathima Nizar",
    nic: "198854321V",
    phone: "075 220 1188",
    product: "Housing Repair",
    group: "Ganemulla Cluster B",
    disbursed: "2025-08-12",
    outstanding: 198000,
    installment: 6800,
    cycle: "Bi-weekly",
    officer: OFFICER.name,
    distressProbability: 64,
    threshold: 60,
    paymentVelocity: {
      unit: "days late",
      slopeLabel: "Worsening at 1.3 days per installment",
      series: [0, 0, 1, 2, 4, 6, 8],
    },
    socialDecay: {
      unit: "group engagement score",
      slopeLabel: "Decaying at −8.4 points per cycle",
      series: [96, 90, 78, 65, 54, 41, 33],
    },
    correlation: {
      aligned: true,
      label: "Both signals declining simultaneously — Compounding Risk",
    },
  },
}

export const LOAN_DETAILS = {
  "LN-88421": {
    id: "LN-88421",
    borrower: "Kumari Fernando",
    nic: "198765432V",
    phone: "077 412 8891",
    product: "Group Enterprise",
    groupId: "GRP-KIR-12",
    group: "Kirindivita Women's Group 12",
    disbursed: "2025-11-04",
    principal: 100000,
    outstanding: 86500,
    installment: 3500,
    cycle: "Weekly",
    tenureWeeks: 32,
    status: "ews",
    daysLate: 12,
    alertId: "EWS-1042",
    village: "Kirindivita",
    purpose: "Grocery stall working capital",
    interventions: [
      {
        id: "INT-1",
        date: "2026-08-14",
        type: "Phone Call",
        outcome: "Promised payment next market day",
      },
      {
        id: "INT-2",
        date: "2026-08-07",
        type: "Field Visit",
        outcome: "Not home — neighbour confirmed illness",
      },
    ],
    schedule: [
      { id: 1, due: "2026-07-03", amount: 3500, paid: 3500, status: "paid" },
      { id: 2, due: "2026-07-10", amount: 3500, paid: 3500, status: "paid" },
      { id: 3, due: "2026-07-17", amount: 3500, paid: 2000, status: "partial" },
      { id: 4, due: "2026-07-24", amount: 3500, paid: 0, status: "late" },
      { id: 5, due: "2026-07-31", amount: 3500, paid: 0, status: "late" },
      { id: 6, due: "2026-08-07", amount: 3500, paid: 0, status: "late" },
      { id: 7, due: "2026-08-14", amount: 3500, paid: 0, status: "late" },
      { id: 8, due: "2026-08-21", amount: 3500, paid: 0, status: "due" },
      { id: 9, due: "2026-08-28", amount: 3500, paid: 0, status: "upcoming" },
      { id: 10, due: "2026-09-04", amount: 3500, paid: 0, status: "upcoming" },
    ],
  },
  "LN-88390": {
    id: "LN-88390",
    borrower: "Ruwan Perera",
    nic: "199145678V",
    phone: "071 223 4410",
    product: "Individual Working Capital",
    groupId: null,
    group: "Individual",
    disbursed: "2026-01-20",
    principal: 150000,
    outstanding: 124000,
    installment: 5100,
    cycle: "Monthly",
    tenureWeeks: 36,
    status: "current",
    daysLate: 0,
    alertId: null,
    village: "Miriswatta",
    purpose: "Three-wheeler spare parts stock",
    interventions: [],
    schedule: [
      { id: 1, due: "2026-02-20", amount: 5100, paid: 5100, status: "paid" },
      { id: 2, due: "2026-03-20", amount: 5100, paid: 5100, status: "paid" },
      { id: 3, due: "2026-04-20", amount: 5100, paid: 5100, status: "paid" },
      { id: 4, due: "2026-05-20", amount: 5100, paid: 5100, status: "paid" },
      { id: 5, due: "2026-06-20", amount: 5100, paid: 5100, status: "paid" },
      { id: 6, due: "2026-07-20", amount: 5100, paid: 5100, status: "paid" },
      { id: 7, due: "2026-08-22", amount: 5100, paid: 0, status: "due" },
      { id: 8, due: "2026-09-22", amount: 5100, paid: 0, status: "upcoming" },
    ],
  },
  "LN-88211": {
    id: "LN-88211",
    borrower: "Sanduni Wickramasinghe",
    nic: "199012345V",
    phone: "071 556 2204",
    product: "Agricultural Seasonal",
    groupId: null,
    group: "Individual",
    disbursed: "2026-02-18",
    principal: 75000,
    outstanding: 54000,
    installment: 4200,
    cycle: "Monthly",
    tenureWeeks: 24,
    status: "overdue",
    daysLate: 34,
    alertId: "EWS-1038",
    village: "Yakkala",
    purpose: "Paddy season inputs",
    interventions: [
      {
        id: "INT-3",
        date: "2026-08-18",
        type: "Field Visit",
        outcome: "Crop delayed — partial payment expected after harvest",
      },
    ],
    schedule: [
      { id: 1, due: "2026-03-18", amount: 4200, paid: 4200, status: "paid" },
      { id: 2, due: "2026-04-18", amount: 4200, paid: 4200, status: "paid" },
      { id: 3, due: "2026-05-18", amount: 4200, paid: 2100, status: "partial" },
      { id: 4, due: "2026-06-18", amount: 4200, paid: 0, status: "late" },
      { id: 5, due: "2026-07-18", amount: 4200, paid: 0, status: "late" },
      { id: 6, due: "2026-08-18", amount: 4200, paid: 0, status: "late" },
      { id: 7, due: "2026-09-18", amount: 4200, paid: 0, status: "upcoming" },
    ],
  },
  "LN-88104": {
    id: "LN-88104",
    borrower: "Ajith Bandara",
    nic: "198556789V",
    phone: "077 889 1102",
    product: "Group Enterprise",
    groupId: "GRP-KIR-12",
    group: "Kirindivita Women's Group 12",
    disbursed: "2026-03-12",
    principal: 50000,
    outstanding: 31200,
    installment: 2800,
    cycle: "Weekly",
    tenureWeeks: 20,
    status: "current",
    daysLate: 0,
    alertId: null,
    village: "Kirindivita",
    purpose: "Snack cart expansion",
    interventions: [],
    schedule: [
      { id: 1, due: "2026-07-31", amount: 2800, paid: 2800, status: "paid" },
      { id: 2, due: "2026-08-07", amount: 2800, paid: 2800, status: "paid" },
      { id: 3, due: "2026-08-14", amount: 2800, paid: 2800, status: "paid" },
      { id: 4, due: "2026-08-23", amount: 2800, paid: 0, status: "due" },
      { id: 5, due: "2026-08-30", amount: 2800, paid: 0, status: "upcoming" },
    ],
  },
  "LN-88077": {
    id: "LN-88077",
    borrower: "Fathima Nizar",
    nic: "198854321V",
    phone: "075 220 1188",
    product: "Housing Repair",
    groupId: "GRP-GAN-B",
    group: "Ganemulla Cluster B",
    disbursed: "2025-08-12",
    principal: 250000,
    outstanding: 198000,
    installment: 6800,
    cycle: "Bi-weekly",
    tenureWeeks: 48,
    status: "ews",
    daysLate: 8,
    alertId: "EWS-1045",
    village: "Ganemulla",
    purpose: "Roof and wall repair",
    interventions: [
      {
        id: "INT-4",
        date: "2026-08-20",
        type: "Phone Call",
        outcome: "Spouse lost job — considering restructure",
      },
    ],
    schedule: [
      { id: 1, due: "2026-06-24", amount: 6800, paid: 6800, status: "paid" },
      { id: 2, due: "2026-07-08", amount: 6800, paid: 6800, status: "paid" },
      { id: 3, due: "2026-07-22", amount: 6800, paid: 3400, status: "partial" },
      { id: 4, due: "2026-08-05", amount: 6800, paid: 0, status: "late" },
      { id: 5, due: "2026-08-19", amount: 6800, paid: 0, status: "late" },
      { id: 6, due: "2026-09-02", amount: 6800, paid: 0, status: "upcoming" },
    ],
  },
}

export const OVERDUE_QUEUE = [
  {
    id: "LN-88211",
    borrower: "Sanduni Wickramasinghe",
    product: "Agricultural Seasonal",
    outstanding: 54000,
    amountDue: 12600,
    daysLate: 34,
    parBucket: "PAR30",
    village: "Yakkala",
    alertId: "EWS-1038",
  },
  {
    id: "LN-88421",
    borrower: "Kumari Fernando",
    product: "Group Enterprise",
    outstanding: 86500,
    amountDue: 14000,
    daysLate: 12,
    parBucket: "PAR1-30",
    village: "Kirindivita",
    alertId: "EWS-1042",
  },
  {
    id: "LN-88077",
    borrower: "Fathima Nizar",
    product: "Housing Repair",
    outstanding: 198000,
    amountDue: 13600,
    daysLate: 8,
    parBucket: "PAR1-30",
    village: "Ganemulla",
    alertId: "EWS-1045",
  },
  {
    id: "LN-87990",
    borrower: "Chaminda Silva",
    product: "Individual Working Capital",
    outstanding: 42000,
    amountDue: 8500,
    daysLate: 41,
    parBucket: "PAR30",
    village: "Yakkala",
    alertId: null,
  },
  {
    id: "LN-87812",
    borrower: "Nilani Perera",
    product: "Group Enterprise",
    outstanding: 28500,
    amountDue: 5600,
    daysLate: 19,
    parBucket: "PAR1-30",
    village: "Miriswatta",
    alertId: null,
  },
]

export const GROUPS = {
  "GRP-KIR-12": {
    id: "GRP-KIR-12",
    name: "Kirindivita Women's Group 12",
    village: "Kirindivita",
    formed: "2024-06-18",
    guaranteeStrength: 78,
    meetingAttendance: 61,
    members: [
      {
        name: "Kumari Fernando",
        loanId: "LN-88421",
        role: "Chair",
        outstanding: 86500,
        status: "ews",
      },
      {
        name: "Ajith Bandara",
        loanId: "LN-88104",
        role: "Member",
        outstanding: 31200,
        status: "current",
      },
      {
        name: "Samanthi Dias",
        loanId: "LN-87701",
        role: "Treasurer",
        outstanding: 44800,
        status: "current",
      },
      {
        name: "Ranjani Wijesinghe",
        loanId: "LN-87655",
        role: "Member",
        outstanding: 22100,
        status: "current",
      },
      {
        name: "Malathi Gunasekara",
        loanId: null,
        role: "Guarantor",
        outstanding: 0,
        status: "guarantor",
      },
    ],
  },
  "GRP-GAN-B": {
    id: "GRP-GAN-B",
    name: "Ganemulla Cluster B",
    village: "Ganemulla",
    formed: "2023-11-02",
    guaranteeStrength: 54,
    meetingAttendance: 41,
    members: [
      {
        name: "Fathima Nizar",
        loanId: "LN-88077",
        role: "Chair",
        outstanding: 198000,
        status: "ews",
      },
      {
        name: "Hassan Mohamed",
        loanId: "LN-87520",
        role: "Member",
        outstanding: 67000,
        status: "current",
      },
      {
        name: "Shirani Fernando",
        loanId: "LN-87488",
        role: "Member",
        outstanding: 39000,
        status: "overdue",
      },
    ],
  },
}

export const BRANCHES = {
  "br-gampaha": {
    id: "br-gampaha",
    branch: "Gampaha Central",
    manager: "Nimal Silva",
    stats: {
      activeLoans: 186,
      ewsAlertCount: 22,
      overdueCount: 31,
      par30: 5.8,
      collectionRate: 91.2,
      officers: 4,
    },
    officers: [
      {
        name: "Nuwan Jayasuriya",
        portfolioId: "PF-GAM-014",
        activeLoans: 48,
        ews: 7,
        overdue: 11,
        par30: 6.4,
      },
      {
        name: "Malkanthi Rathnayake",
        portfolioId: "PF-GAM-021",
        activeLoans: 52,
        ews: 5,
        overdue: 8,
        par30: 4.9,
      },
      {
        name: "Dinesh Ranatunga",
        portfolioId: "PF-GAM-033",
        activeLoans: 41,
        ews: 6,
        overdue: 7,
        par30: 5.2,
      },
      {
        name: "Chandana Weerasinghe",
        portfolioId: "PF-GAM-041",
        activeLoans: 45,
        ews: 4,
        overdue: 5,
        par30: 6.1,
      },
    ],
    topAlerts: [
      { id: "EWS-1038", borrower: "Sanduni Wickramasinghe", officer: "Nuwan Jayasuriya", probability: 86 },
      { id: "EWS-1042", borrower: "Kumari Fernando", officer: "Nuwan Jayasuriya", probability: 78 },
      { id: "EWS-1045", borrower: "Fathima Nizar", officer: "Nuwan Jayasuriya", probability: 64 },
      { id: "EWS-1051", borrower: "Shirani Fernando", officer: "Malkanthi Rathnayake", probability: 71 },
    ],
  },
  "br-kandy": {
    id: "br-kandy",
    branch: "Kandy Branch",
    manager: "Sunil Bandara",
    stats: {
      activeLoans: 142,
      ewsAlertCount: 14,
      overdueCount: 19,
      par30: 4.2,
      collectionRate: 94.1,
      officers: 3,
    },
    officers: [
      {
        name: "Amila Bandara",
        portfolioId: "PF-KAN-008",
        activeLoans: 51,
        ews: 4,
        overdue: 6,
        par30: 3.8,
      },
      {
        name: "Tharindu Perera",
        portfolioId: "PF-KAN-012",
        activeLoans: 47,
        ews: 5,
        overdue: 7,
        par30: 4.5,
      },
      {
        name: "Sewwandi Jayawardena",
        portfolioId: "PF-KAN-019",
        activeLoans: 44,
        ews: 5,
        overdue: 6,
        par30: 4.3,
      },
    ],
    topAlerts: [
      { id: "EWS-1042", borrower: "Kumari Fernando", officer: "Amila Bandara", probability: 78 },
      { id: "EWS-1045", borrower: "Fathima Nizar", officer: "Tharindu Perera", probability: 64 },
    ],
  },
  "br-colombo": {
    id: "br-colombo",
    branch: "Colombo Head Office",
    manager: "Kamal Perera",
    stats: {
      activeLoans: 210,
      ewsAlertCount: 18,
      overdueCount: 24,
      par30: 3.9,
      collectionRate: 92.6,
      officers: 5,
    },
    officers: [
      {
        name: "Kasun Silva",
        portfolioId: "PF-CMB-003",
        activeLoans: 55,
        ews: 3,
        overdue: 4,
        par30: 3.1,
      },
      {
        name: "Ruwanthi Rajapaksha",
        portfolioId: "PF-CMB-011",
        activeLoans: 49,
        ews: 5,
        overdue: 6,
        par30: 4.0,
      },
      {
        name: "Saman Kumara",
        portfolioId: "PF-CMB-015",
        activeLoans: 38,
        ews: 4,
        overdue: 5,
        par30: 4.2,
      },
      {
        name: "Nadeesha Fernando",
        portfolioId: "PF-CMB-022",
        activeLoans: 42,
        ews: 3,
        overdue: 5,
        par30: 3.7,
      },
      {
        name: "Ishara Wickrama",
        portfolioId: "PF-CMB-028",
        activeLoans: 26,
        ews: 3,
        overdue: 4,
        par30: 4.4,
      },
    ],
    topAlerts: [
      { id: "EWS-1038", borrower: "Sanduni Wickramasinghe", officer: "Ruwanthi Rajapaksha", probability: 86 },
      { id: "EWS-1042", borrower: "Kumari Fernando", officer: "Kasun Silva", probability: 78 },
    ],
  },
  "br-galle": {
    id: "br-galle",
    branch: "Galle Branch",
    manager: "Kumari Fernando",
    stats: {
      activeLoans: 98,
      ewsAlertCount: 11,
      overdueCount: 15,
      par30: 7.1,
      collectionRate: 88.4,
      officers: 2,
    },
    officers: [
      {
        name: "Chandana Weerasinghe",
        portfolioId: "PF-GAL-006",
        activeLoans: 52,
        ews: 6,
        overdue: 9,
        par30: 7.4,
      },
      {
        name: "Malkanthi Rathnayake",
        portfolioId: "PF-GAL-009",
        activeLoans: 46,
        ews: 5,
        overdue: 6,
        par30: 6.8,
      },
    ],
    topAlerts: [
      { id: "EWS-1045", borrower: "Fathima Nizar", officer: "Chandana Weerasinghe", probability: 64 },
      { id: "EWS-1038", borrower: "Sanduni Wickramasinghe", officer: "Malkanthi Rathnayake", probability: 86 },
    ],
  },
}

export const BRANCH_LIST = Object.values(BRANCHES)

/** @deprecated use BRANCHES — kept for any leftover imports */
export const BRANCH_PORTFOLIO = BRANCHES["br-gampaha"]

export const EWS_ALERT_LIST = Object.values(ALERTS).map((alert) => ({
  id: alert.id,
  loanId: alert.loanId,
  borrower: alert.borrower,
  product: alert.product,
  distressProbability: alert.distressProbability,
  daysLate: alert.paymentVelocity?.series?.at(-1) ?? 0,
  outstanding: alert.outstanding,
}))

export function formatLkr(value) {
  return `LKR ${Number(value).toLocaleString("en-LK")}`
}

export function scheduleStatusBadge(status) {
  if (status === "paid") return { label: "Paid", variant: "secondary" }
  if (status === "partial") return { label: "Partial", variant: "outline" }
  if (status === "late") return { label: "Late", variant: "destructive" }
  if (status === "due") return { label: "Due", variant: "default" }
  return { label: "Upcoming", variant: "muted" }
}
